version: '3.5'

services:
  api:
    container_name: payment_service
    network_mode: bridge
    links:
      - db
    build:
      context: ./
      dockerfile: app/Dockerfile
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./app:/usr/src/app
    ports:
      - 23102:5000
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_APP: app.py
  db:
    image: mysql:5.7
    network_mode: bridge
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
